# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60670d1cdc3aab0a5f97738beece02f0a426b43829f64df6abe865430aef340e1b516d1e63e2be31bee2740846f0110a5de2f984f7e1e13b52b5be085840aed5

test:
  secret_key_base: 60229d55f72939843fbf124f1e4b17cd0d513bf51cc7290798fec58cc426d4a84aecea4b7ab53f8352882dd1f1cbeb9f3f5307d5d5dfdd44a9c8fa3396199f49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
